name: on Push main 
on: 
  push:
    branches:
      - main
jobs: 
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USR}}
          password: ${{ secrets.DOCKERHUB_PWD}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gitlantis/user-test-api-main:latest, gitlantis/user-test-api-main:${{github.run_number}}
      - name: Send Webhook
        run: |
          WEBHOOK_URL=${{ vars.WEBHOOK_URL }}
          curl -X POST -H "Content-Type: application/json" -d '{"message": "GitHub workflow completed!"}' $WEBHOOK_URL
