name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:

  build-container:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v3
    - name: Login to docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USR}}
        password: ${{secrets.DOCKERHUB_PSW}}
    - name: Build and push docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gitlantis/test-user-api-prod:latest, gitlantis/test-user-api-prod:${{github.run_number}}
